version: '3.8'

services:
  dev-crm-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pastis
      POSTGRES_DB: crm
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5434:5432

volumes:
  postgres_data:
